#!/usr/bin/env bash
# One-command local setup: Postgres (Docker) → env → install → migrate → seed → dev server.
#
#   bash scripts/fresh-start.sh            # full setup, then starts `npm run dev`
#   bash scripts/fresh-start.sh --no-dev   # setup only
#   bash scripts/fresh-start.sh --reset    # wipe the local DB volume first (destructive)
#
# Needs: Node >= 20.9, npm, Docker (with the compose plugin). On Windows use Git Bash or WSL.
set -euo pipefail
cd "$(dirname "$0")/.."

START_DEV=1
RESET=0
for arg in "$@"; do
  case "$arg" in
    --no-dev) START_DEV=0 ;;
    --reset)  RESET=1 ;;
    *) echo "Unknown option: $arg"; exit 1 ;;
  esac
done

say() { printf '\n\033[1;36m▶ %s\033[0m\n' "$*"; }
die() { printf '\n\033[1;31m✖ %s\033[0m\n' "$*" >&2; exit 1; }

# ── 1. prerequisites ────────────────────────────────────────────────────────
command -v node   >/dev/null || die "Node.js is not installed (need >= 20.9). Try: nvm install 22"
command -v npm    >/dev/null || die "npm is not installed."
command -v docker >/dev/null || die "Docker is not installed (needed for the local Postgres). https://docs.docker.com/get-docker/"
docker compose version >/dev/null 2>&1 || die "'docker compose' plugin not found. Update Docker Desktop / install docker-compose-plugin."
docker info >/dev/null 2>&1 || die "Docker is installed but not running. Start Docker Desktop / the docker daemon."

node -e 'const [a,b]=process.versions.node.split(".").map(Number); process.exit(a>20||(a===20&&b>=9)?0:1)' \
  || die "Node $(node -v) is too old — need >= 20.9 (Node 22 recommended)."

# ── 2. database ─────────────────────────────────────────────────────────────
if [ "$RESET" = "1" ]; then
  say "Resetting local database volume"
  docker compose down -v
fi

say "Starting Postgres (docker compose)"
docker compose up -d db

say "Waiting for Postgres to be ready"
for i in $(seq 1 40); do
  if docker compose exec -T db pg_isready -U club -d club >/dev/null 2>&1; then break; fi
  [ "$i" = "40" ] && die "Postgres did not become ready in time. Check: docker compose logs db"
  sleep 1
done

# ── 3. env file ─────────────────────────────────────────────────────────────
# Prisma CLI only reads `.env` (not `.env.local`), Next reads both — so we use
# `.env` for a fresh setup. If you already have a `.env.local`, we respect it.
if [ -f .env.local ]; then
  ENV_FILE=".env.local"
elif [ -f .env ]; then
  ENV_FILE=".env"
else
  ENV_FILE=".env"
  say "Creating .env with local defaults and freshly generated secrets"
  JWT="$(node -e 'console.log(require("crypto").randomBytes(48).toString("base64"))')"
  CRON="$(node -e 'console.log(require("crypto").randomBytes(32).toString("hex"))')"
  cat > .env <<ENVEOF
# Generated by scripts/fresh-start.sh — local development only.
DATABASE_URL="postgresql://club:club@localhost:5433/club"
DIRECT_URL="postgresql://club:club@localhost:5433/club"
APP_URL="http://localhost:3000"
NEXT_PUBLIC_APP_URL="http://localhost:3000"
JWT_SECRET="${JWT}"
CRON_SECRET="${CRON}"

# Tenant routing in dev: club-a.localhost:3000 = gym A, club-b.localhost:3000 = gym B,
# plain localhost:3000 = platform (landing page + super-admin login).
# Leave DEV_DEFAULT_CLUB_SLUG unset — setting it makes plain localhost behave as a
# gym, which makes the super-admin login impossible.

# Optional — the app runs without these (see .env.example for the full list):
#   UPSTASH_REDIS_REST_URL / UPSTASH_REDIS_REST_TOKEN  → distributed rate limit + SSE
#   BREVO_API_KEY                                      → real emails (otherwise printed in this terminal)
#   CLOUDINARY_*                                       → image uploads
#   KONNECT_*                                          → online payments
ENVEOF
fi
echo "Using env file: $ENV_FILE"

# Export everything so the Prisma CLI + seed see the same variables Next does.
set -a
# shellcheck disable=SC1090
. "./$ENV_FILE"
set +a

# ── 4. install / generate / migrate / seed ──────────────────────────────────
say "Installing dependencies (npm ci)"
npm ci --no-audit --no-fund

say "Generating Prisma client"
npx prisma generate

say "Applying database migrations"
npx prisma migrate deploy

say "Seeding demo data (2 clubs, plans, demo accounts)"
npx prisma db seed

cat <<'DONE'

────────────────────────────────────────────────────────────────────────────
  ✅  Ready.

  Gym A (club-a)   http://club-a.localhost:3000     ← Chrome / Firefox / Edge
  Gym B (club-b)   http://club-b.localhost:3000       (Safari: add both hosts to /etc/hosts)
  Platform         http://localhost:3000            ← landing page, /onboarding, /platform/login

  Logins — password for ALL accounts: Demo123!
    Owner   A   owner.a@demo.local     (club-a.localhost:3000/user/login)
    Admin   A   admin.a@demo.local
    Coach   A   coach.a@demo.local
    Member  A   member.a@demo.local
    Owner   B   owner.b@demo.local     (club-b.localhost:3000/user/login)
    Super admin superadmin@platform.local  (localhost:3000/platform/login)

  Emails (verification, resets…) are printed in THIS terminal until you set BREVO_API_KEY.
────────────────────────────────────────────────────────────────────────────
DONE

if [ "$START_DEV" = "1" ]; then
  say "Starting dev server"
  exec npm run dev
fi
