-- ============================================================================
-- Phase 2: Multi-tenancy migration
--
-- IMPORTANT — READ BEFORE RUNNING:
-- This was written by hand, not generated by `prisma migrate dev`, because
-- this sandbox has no network access to a live Postgres instance or to
-- Prisma's engine binaries. Before applying to any real database:
--
--   1. BACK UP the database first. This migration is not reversible as
--      written (no down-migration is provided).
--   2. Run it against a staging copy of production data first, not prod
--      directly.
--   3. After applying, run `npx prisma validate` and `npx prisma generate`
--      and confirm they succeed, then run the app's test suite.
--   4. If you'd rather have Prisma generate/verify this migration itself,
--      you can instead: (a) apply schema.prisma's changes, (b) run
--      `npx prisma migrate dev --create-only` to let Prisma generate its
--      own migration.sql, then (c) manually merge in the data-backfill
--      block below (Prisma will NOT write the backfill logic for you —
--      it only knows how to add/drop columns and constraints, not how to
--      populate them from existing rows).
--
-- Strategy used throughout: add columns NULLABLE first, backfill data,
-- THEN add NOT NULL/foreign-key/unique constraints. This is the standard
-- zero-downtime pattern and avoids the migration failing outright on a
-- database that already has rows (a plain `ADD COLUMN "clubId" TEXT NOT
-- NULL` would fail immediately on any table with existing data).
-- ============================================================================


-- ── 1. New enums ────────────────────────────────────────────────────────────

CREATE TYPE "ClubStatus" AS ENUM ('TRIAL', 'ACTIVE', 'SUSPENDED', 'CANCELLED');
CREATE TYPE "SaasPlanTier" AS ENUM ('STARTER', 'PRO', 'BUSINESS');
CREATE TYPE "PlatformSubscriptionStatus" AS ENUM ('TRIALING', 'ACTIVE', 'PAST_DUE', 'CANCELED', 'SUSPENDED');

-- Postgres requires adding enum values outside of a transaction in older
-- versions; on PG12+ this works fine inside `prisma migrate deploy`'s
-- transaction. If your Postgres is older than 12, run this single line
-- separately before the rest of the migration.
ALTER TYPE "Role" ADD VALUE 'SUPER_ADMIN';


-- ── 2. New tables: clubs, saas_plans, club_subscriptions ───────────────────

CREATE TABLE "clubs" (
    "id" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "status" "ClubStatus" NOT NULL DEFAULT 'TRIAL',
    "customDomain" TEXT,
    "trialEndsAt" TIMESTAMP(3),
    "suspendedAt" TIMESTAMP(3),
    "suspendedReason" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "clubs_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "clubs_slug_key" ON "clubs"("slug");
CREATE UNIQUE INDEX "clubs_customDomain_key" ON "clubs"("customDomain");
CREATE INDEX "clubs_status_idx" ON "clubs"("status");

CREATE TABLE "saas_plans" (
    "id" TEXT NOT NULL,
    "tier" "SaasPlanTier" NOT NULL,
    "name" TEXT NOT NULL,
    "priceMonthly" DOUBLE PRECISION NOT NULL,
    "currency" TEXT NOT NULL DEFAULT 'USD',
    "limits" JSONB NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "saas_plans_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "saas_plans_tier_key" ON "saas_plans"("tier");

CREATE TABLE "club_subscriptions" (
    "id" TEXT NOT NULL,
    "clubId" TEXT NOT NULL,
    "planId" TEXT NOT NULL,
    "status" "PlatformSubscriptionStatus" NOT NULL DEFAULT 'TRIALING',
    "trialEndsAt" TIMESTAMP(3),
    "currentPeriodStart" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "currentPeriodEnd" TIMESTAMP(3),
    "cancelAtPeriodEnd" BOOLEAN NOT NULL DEFAULT false,
    "canceledAt" TIMESTAMP(3),
    "providerCustomerId" TEXT,
    "providerSubscriptionId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "club_subscriptions_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "club_subscriptions_clubId_key" ON "club_subscriptions"("clubId");
CREATE INDEX "club_subscriptions_planId_idx" ON "club_subscriptions"("planId");
CREATE INDEX "club_subscriptions_status_idx" ON "club_subscriptions"("status");
ALTER TABLE "club_subscriptions" ADD CONSTRAINT "club_subscriptions_clubId_fkey" FOREIGN KEY ("clubId") REFERENCES "clubs"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "club_subscriptions" ADD CONSTRAINT "club_subscriptions_planId_fkey" FOREIGN KEY ("planId") REFERENCES "saas_plans"("id") ON DELETE RESTRICT ON UPDATE CASCADE;


-- ── 3. Seed the SaaS plan catalog + one default Club for existing data ─────
-- This is the tenant every pre-existing row will be assigned to below, so
-- the currently-running single gym keeps working exactly as before, just
-- now living inside Club "default-gym" instead of implicitly being "the
-- only gym". Rename it via the admin dashboard once Phase 8 (onboarding)
-- ships an editable name/slug — this INSERT is only to make existing data
-- valid immediately.

INSERT INTO "saas_plans" ("id", "tier", "name", "priceMonthly", "currency", "limits", "updatedAt") VALUES
  ('plan_starter', 'STARTER', 'Starter', 29, 'USD',
   '{"maxMembers":100,"maxCoaches":3,"maxAdmins":2,"storageGB":2,"maxBookingsPerMonth":500,"maxCustomPages":3,"customDomain":false,"advancedAnalytics":false,"revenueAnalytics":false,"apiAccess":false,"whiteLabel":false}',
   CURRENT_TIMESTAMP),
  ('plan_pro', 'PRO', 'Pro', 79, 'USD',
   '{"maxMembers":500,"maxCoaches":15,"maxAdmins":10,"storageGB":10,"maxBookingsPerMonth":3000,"maxCustomPages":10,"customDomain":true,"advancedAnalytics":true,"revenueAnalytics":true,"apiAccess":false,"whiteLabel":false}',
   CURRENT_TIMESTAMP),
  ('plan_business', 'BUSINESS', 'Business', 199, 'USD',
   '{"maxMembers":null,"maxCoaches":null,"maxAdmins":null,"storageGB":50,"maxBookingsPerMonth":null,"maxCustomPages":null,"customDomain":true,"advancedAnalytics":true,"revenueAnalytics":true,"apiAccess":true,"whiteLabel":true}',
   CURRENT_TIMESTAMP);

INSERT INTO "clubs" ("id", "slug", "name", "status", "updatedAt") VALUES
  ('default-gym', 'default', COALESCE((SELECT "name" FROM "gym_settings" LIMIT 1), 'Le Club de Gammarth'), 'ACTIVE', CURRENT_TIMESTAMP);

INSERT INTO "club_subscriptions" ("id", "clubId", "planId", "status", "currentPeriodStart", "updatedAt") VALUES
  ('sub_default-gym', 'default-gym', 'plan_business', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


-- ── 4. Add clubId columns (nullable first) to every gym-owned table ───────

ALTER TABLE "users" ADD COLUMN "clubId" TEXT;
ALTER TABLE "membership_plans" ADD COLUMN "clubId" TEXT;
ALTER TABLE "subscriptions" ADD COLUMN "clubId" TEXT;
ALTER TABLE "payments" ADD COLUMN "clubId" TEXT;
ALTER TABLE "weekly_plans" ADD COLUMN "clubId" TEXT;
ALTER TABLE "sessions" ADD COLUMN "clubId" TEXT;
ALTER TABLE "coaches" ADD COLUMN "clubId" TEXT;
ALTER TABLE "user_sessions" ADD COLUMN "clubId" TEXT;
ALTER TABLE "membership_cards" ADD COLUMN "clubId" TEXT;
ALTER TABLE "attendances" ADD COLUMN "clubId" TEXT;
ALTER TABLE "notifications" ADD COLUMN "clubId" TEXT;
ALTER TABLE "posts" ADD COLUMN "clubId" TEXT;
ALTER TABLE "promotions" ADD COLUMN "clubId" TEXT;
ALTER TABLE "gym_settings" ADD COLUMN "clubId" TEXT;
ALTER TABLE "page_content" ADD COLUMN "clubId" TEXT;
ALTER TABLE "role_permissions" ADD COLUMN "clubId" TEXT;
ALTER TABLE "member_reports" ADD COLUMN "clubId" TEXT;
-- ActivityLog.clubId stays nullable permanently (platform-level actions
-- have no club), so no backfill/NOT NULL step needed for it — just add it.
ALTER TABLE "activity_logs" ADD COLUMN "clubId" TEXT;


-- ── 5. Backfill: every existing row belongs to the one default Club ───────

UPDATE "users" SET "clubId" = 'default-gym';
UPDATE "membership_plans" SET "clubId" = 'default-gym';
UPDATE "subscriptions" SET "clubId" = 'default-gym';
UPDATE "payments" SET "clubId" = 'default-gym';
UPDATE "weekly_plans" SET "clubId" = 'default-gym';
UPDATE "sessions" SET "clubId" = 'default-gym';
UPDATE "coaches" SET "clubId" = 'default-gym';
UPDATE "user_sessions" SET "clubId" = 'default-gym';
UPDATE "membership_cards" SET "clubId" = 'default-gym';
UPDATE "attendances" SET "clubId" = 'default-gym';
UPDATE "notifications" SET "clubId" = 'default-gym';
UPDATE "posts" SET "clubId" = 'default-gym';
UPDATE "promotions" SET "clubId" = 'default-gym';
UPDATE "gym_settings" SET "clubId" = 'default-gym';
UPDATE "page_content" SET "clubId" = 'default-gym';
UPDATE "role_permissions" SET "clubId" = 'default-gym';
UPDATE "member_reports" SET "clubId" = 'default-gym';


-- ── 6. Enforce NOT NULL now that every row has a value ─────────────────────
-- users.clubId stays NULLABLE (SUPER_ADMIN accounts have none). Every other
-- table below is gym-owned and always belongs to exactly one Club.

ALTER TABLE "membership_plans" ALTER COLUMN "clubId" SET NOT NULL;
ALTER TABLE "subscriptions" ALTER COLUMN "clubId" SET NOT NULL;
ALTER TABLE "payments" ALTER COLUMN "clubId" SET NOT NULL;
ALTER TABLE "weekly_plans" ALTER COLUMN "clubId" SET NOT NULL;
ALTER TABLE "sessions" ALTER COLUMN "clubId" SET NOT NULL;
ALTER TABLE "coaches" ALTER COLUMN "clubId" SET NOT NULL;
ALTER TABLE "user_sessions" ALTER COLUMN "clubId" SET NOT NULL;
ALTER TABLE "membership_cards" ALTER COLUMN "clubId" SET NOT NULL;
ALTER TABLE "attendances" ALTER COLUMN "clubId" SET NOT NULL;
ALTER TABLE "notifications" ALTER COLUMN "clubId" SET NOT NULL;
ALTER TABLE "posts" ALTER COLUMN "clubId" SET NOT NULL;
ALTER TABLE "promotions" ALTER COLUMN "clubId" SET NOT NULL;
ALTER TABLE "gym_settings" ALTER COLUMN "clubId" SET NOT NULL;
ALTER TABLE "page_content" ALTER COLUMN "clubId" SET NOT NULL;
ALTER TABLE "role_permissions" ALTER COLUMN "clubId" SET NOT NULL;
ALTER TABLE "member_reports" ALTER COLUMN "clubId" SET NOT NULL;


-- ── 7. Foreign keys ─────────────────────────────────────────────────────────

ALTER TABLE "users" ADD CONSTRAINT "users_clubId_fkey" FOREIGN KEY ("clubId") REFERENCES "clubs"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "membership_plans" ADD CONSTRAINT "membership_plans_clubId_fkey" FOREIGN KEY ("clubId") REFERENCES "clubs"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "subscriptions" ADD CONSTRAINT "subscriptions_clubId_fkey" FOREIGN KEY ("clubId") REFERENCES "clubs"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "payments" ADD CONSTRAINT "payments_clubId_fkey" FOREIGN KEY ("clubId") REFERENCES "clubs"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "weekly_plans" ADD CONSTRAINT "weekly_plans_clubId_fkey" FOREIGN KEY ("clubId") REFERENCES "clubs"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_clubId_fkey" FOREIGN KEY ("clubId") REFERENCES "clubs"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "coaches" ADD CONSTRAINT "coaches_clubId_fkey" FOREIGN KEY ("clubId") REFERENCES "clubs"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "user_sessions" ADD CONSTRAINT "user_sessions_clubId_fkey" FOREIGN KEY ("clubId") REFERENCES "clubs"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "membership_cards" ADD CONSTRAINT "membership_cards_clubId_fkey" FOREIGN KEY ("clubId") REFERENCES "clubs"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "attendances" ADD CONSTRAINT "attendances_clubId_fkey" FOREIGN KEY ("clubId") REFERENCES "clubs"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_clubId_fkey" FOREIGN KEY ("clubId") REFERENCES "clubs"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "posts" ADD CONSTRAINT "posts_clubId_fkey" FOREIGN KEY ("clubId") REFERENCES "clubs"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "promotions" ADD CONSTRAINT "promotions_clubId_fkey" FOREIGN KEY ("clubId") REFERENCES "clubs"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "gym_settings" ADD CONSTRAINT "gym_settings_clubId_fkey" FOREIGN KEY ("clubId") REFERENCES "clubs"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "page_content" ADD CONSTRAINT "page_content_clubId_fkey" FOREIGN KEY ("clubId") REFERENCES "clubs"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "role_permissions" ADD CONSTRAINT "role_permissions_clubId_fkey" FOREIGN KEY ("clubId") REFERENCES "clubs"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "member_reports" ADD CONSTRAINT "member_reports_clubId_fkey" FOREIGN KEY ("clubId") REFERENCES "clubs"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "activity_logs" ADD CONSTRAINT "activity_logs_clubId_fkey" FOREIGN KEY ("clubId") REFERENCES "clubs"("id") ON DELETE CASCADE ON UPDATE CASCADE;


-- ── 8. Drop old GLOBAL unique constraints that are now wrong, add scoped ones ─
-- Each of these previously prevented two different gyms from independently
-- using the same code/number/key. Find your actual constraint names first —
-- Prisma's default naming is assumed below (`prisma migrate diff` against
-- your real DB will tell you if they differ):

ALTER TABLE "users" DROP CONSTRAINT IF EXISTS "users_email_key";
CREATE UNIQUE INDEX "users_clubId_email_key" ON "users"("clubId", "email");
-- Composite unique above does NOT stop two SUPER_ADMIN rows (clubId IS NULL)
-- from sharing an email, because Postgres treats NULL <> NULL even inside a
-- unique index. This partial index covers exactly that gap:
CREATE UNIQUE INDEX "users_platform_email_key" ON "users"("email") WHERE "clubId" IS NULL;
CREATE INDEX "users_clubId_idx" ON "users"("clubId");
CREATE INDEX "users_clubId_role_idx" ON "users"("clubId", "role");

ALTER TABLE "weekly_plans" DROP CONSTRAINT IF EXISTS "weekly_plans_weekStart_weekEnd_key";
CREATE UNIQUE INDEX "weekly_plans_clubId_weekStart_weekEnd_key" ON "weekly_plans"("clubId", "weekStart", "weekEnd");
CREATE INDEX "weekly_plans_clubId_idx" ON "weekly_plans"("clubId");

ALTER TABLE "membership_cards" DROP CONSTRAINT IF EXISTS "membership_cards_cardNumber_key";
CREATE UNIQUE INDEX "membership_cards_clubId_cardNumber_key" ON "membership_cards"("clubId", "cardNumber");
CREATE INDEX "membership_cards_clubId_idx" ON "membership_cards"("clubId");

ALTER TABLE "promotions" DROP CONSTRAINT IF EXISTS "promotions_code_key";
CREATE UNIQUE INDEX "promotions_clubId_code_key" ON "promotions"("clubId", "code");
CREATE INDEX "promotions_clubId_idx" ON "promotions"("clubId");

ALTER TABLE "page_content" DROP CONSTRAINT IF EXISTS "page_content_pageKey_key";
CREATE UNIQUE INDEX "page_content_clubId_pageKey_key" ON "page_content"("clubId", "pageKey");
CREATE INDEX "page_content_clubId_idx" ON "page_content"("clubId");

ALTER TABLE "role_permissions" DROP CONSTRAINT IF EXISTS "role_permissions_role_key_key";
CREATE UNIQUE INDEX "role_permissions_clubId_role_key_key" ON "role_permissions"("clubId", "role", "key");
CREATE INDEX "role_permissions_clubId_idx" ON "role_permissions"("clubId");

-- gym_settings had no unique key before (singleton by convention, id was
-- always the literal string 'singleton') — clubId is now its 1:1 key.
-- If your existing row's id is literally 'singleton', that's fine, Prisma
-- doesn't care what the primary key value is, only that clubId is unique:
CREATE UNIQUE INDEX "gym_settings_clubId_key" ON "gym_settings"("clubId");

-- Remaining straightforward indexes:
CREATE INDEX "membership_plans_clubId_idx" ON "membership_plans"("clubId");
CREATE INDEX "subscriptions_clubId_idx" ON "subscriptions"("clubId");
CREATE INDEX "payments_clubId_idx" ON "payments"("clubId");
CREATE INDEX "sessions_clubId_idx" ON "sessions"("clubId");
CREATE INDEX "coaches_clubId_idx" ON "coaches"("clubId");
CREATE INDEX "user_sessions_clubId_idx" ON "user_sessions"("clubId");
CREATE INDEX "attendances_clubId_idx" ON "attendances"("clubId");
CREATE INDEX "notifications_clubId_idx" ON "notifications"("clubId");
CREATE INDEX "posts_clubId_createdAt_idx" ON "posts"("clubId", "createdAt");
CREATE INDEX "member_reports_clubId_idx" ON "member_reports"("clubId");
CREATE INDEX "activity_logs_clubId_idx" ON "activity_logs"("clubId");


-- ============================================================================
-- End of migration. After this runs successfully:
--   1. Verify row counts match pre-migration counts for every table above
--      (nothing should have been dropped).
--   2. Verify every non-SUPER_ADMIN user now has a clubId:
--        SELECT count(*) FROM users WHERE role != 'SUPER_ADMIN' AND "clubId" IS NULL;
--      -> must return 0.
--   3. Create your first real SUPER_ADMIN account by hand (there is no UI
--      for this yet — it's a Phase 3/7 deliverable):
--        UPDATE users SET role = 'SUPER_ADMIN', "clubId" = NULL WHERE email = '<you>';
--      Note: this UPDATE will only succeed once the partial unique index
--      above is in place, since it moves the row out of the per-club
--      uniqueness scope and into the platform one.
-- ============================================================================
